#!/bin/bash

PPWD=`pwd`

remove_p1=
remove() {
    
    if [ ! -f "$PKG_INFO/$remove_p1" ]
    then
	echo " ERROR: file $PKG_INFO/$remove_p1 not found"
	return 1
    fi
    basename "$remove_p1" .bz2
    if [ $? -ne 0 ]
    then
	echo " ERROR: wrong filelist file"
	return 1
    fi
    remove_line_count=`cat "$PKG_INFO/$remove_p1" | bzip2 -d | wc -l`
    remove_i=1
    while [ "$remove_i" -ne "$remove_line_count" ]
    do
	FILENAME=`cat "$PKG_INFO/$remove_p1" | bzip2 -d | sed -ne "$remove_i{p;q}" | sed -e "s/^/$DESTDIR/g"`
	echo -e "rm \"$FILENAME\""
	rm "$FILENAME"
	remove_i=$(( $remove_i + 1 ))
    done

    rm "$PKG_INFO/buildlogs/$remove_p1"
    rm "$PKG_INFO/sums/$remove_p1"
    rm "$PKG_INFO/$remove_p1"

    return 0
}

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'remove' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

. "$AIP_DIR/_aipb_init"

if [ -n "$DESTDIR" -a ! -a "$DESTDIR" ]
then
    echo "*** DESTDIR is set, but does not exists"
    exit 1
fi

if [ -n "$DESTDIR" -a ! -d "$DESTDIR" ]
then
    echo "*** DESTDIR is set, exists, but isn't directory"
    exit 1
fi

cd "$PKG_INFO"
pwd
set -f
echo "searching for: $@"
b_filelist=
for b_i in $@
do
    b_filelist="$b_filelist `find . -maxdepth 1 -type f -name \"$b_i\" -printf \" %f\" ` "
#    find . -maxdepth 1 -type f -name "$b_i" -printf " %f"
done

set +f
echo "found: $b_filelist"

for b_i in $b_filelist
do
    remove_p1="$b_i"
    remove
done

err=$?

ldconfig
     
exit $err