#!/bin/bash

# This script searches all soft links with pwd in the link and removes
# this pwd from link


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

PPWD=`pwd`

links=

find -type l 

j=0
for $i in $links 
do
    echo "$j: $i"
    j="$(( $j + 1 ))"
done
