#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'install' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_extract" ]
then
    echo " ERROR: '$AIP_DIR/_aipb_extract' not found"
    exit 1
fi

OKi=0
ERi=0

for i in $*
do
    if [ -f "$i" ]
    then
	printf "installing: \"$i\"...\n"
	printf "     md5:"
	md5sum -c "$i".md5
	if [ $? -ne 0 ]
	then
	    echo "error"
	    ERi=$(( $ERi + 1 ))
	    continue
	fi

	printf "  sha512:"
	sha512sum -c "$i".sha512
	if [ $? -ne 0 ]
	then
	    echo "error"
	    ERi=$(( $ERi + 1 ))
	    continue
	fi

	echo -n "      installing:"
	bash "$AIP_DIR/_aipb_extract" "$i" "$DESTDIR"/
	if [ $? -eq 0 ]
	then
	    printf ":OK\n"
	    OKi=$(( $OKi + 1 ))
	else
	    printf ":ERROR\n"
	    ERi=$(( $ERi + 1 ))
	fi
    fi
done
echo "  installed: $OKi, errors: $ERi, Total: $(( $OKi + $ERi ))"
echo "  starting ldconfig"
ldconfig
