#!/bin/bash

if [ ! -d "$2" ]
then
    DESTDIR='.'
else
    DESTDIR="$2"
fi

if [ -f "$1" ]
then
    ARCH_TYPE=
#     echo "extracting $1"

    echo "$1" | grep -e '^.*\.tar\.gz$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="tar.gz"
    fi

    echo "$1" | grep -e '^.*\.tar\.bz2$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="tar.bz2"
    fi
    
    echo "$1" | grep -e '^.*\.tar\.lzma$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="tar.lzma"
    fi

    echo "$1" | grep -e '^.*\.tgz$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="tar.gz"
    fi

    echo "$1" | grep -e '^.*\.tar\.7z$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="tar.7z"
    fi

    echo "$1" | grep -e '^.*\.zip$' > /dev/null 2>&1
    if [ $? -eq 0 ]
    then
	ARCH_TYPE="zip"
    fi

    case $ARCH_TYPE in
	'tar.gz')
	    set -o pipefail
	    cat "$1" | gzip -d | tar -xC "$DESTDIR"
	    set +o pipefail
	    fail=$?
	    ;;
	'tar.bz2')
	    set -o pipefail
	    cat "$1" | bzip2 -d | tar -xC "$DESTDIR"
	    set +o pipefail
	    fail=$?
	    ;;
	'tar.lzma')
	    set -o pipefail
	    cat "$1" | lzma -d | tar -xC "$DESTDIR"
	    set +o pipefail
	    fail=$?
	    ;;
	'tar.7z')
	    set -o pipefail
	    7z x -so "$1" | tar -xC "$DESTDIR"
	    set +o pipefail
	    fail=$?
	    ;;
	'zip')
	    unzip -qq "$1" -d "$DESTDIR"
	    fail=$?
	    ;;
	*)
	    echo "unknown extention"
	    exit 1
	    ;;
    esac
    if [ "$fail" -ne 0 ]
    then
	echo "file extraction error"
    fi
    exit $fail
else
    echo "file not exists"
fi
exit 0