#!/bin/bash

#set -x

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_gettempdir" ]
then
    echo " ERROR: '$AIP_DIR/_aipb_gettempdir' not found"
    exit 1
fi

onlyinfo=0
    case "$1" in
	"--help")
	    echo "help"
	    exit 0
	    ;;
	"-u")
	    onlyinfo=1
	    shift
	    echo "only removing info about $1"
	    ;;
    esac

PPWD=`pwd`

remove_p1=
remove() {
    
    if [ ! -f "$PKG_INFO/$remove_p1" ]
    then
	echo " ERROR: file $PKG_INFO/$remove_p1 not found"
	return 1
    fi
    basename "$remove_p1" .bz2
    if [ $? -ne 0 ]
    then
	echo " ERROR: wrong filelist file"
	return 1
    fi

    if [ $onlyinfo -ne 1 ]
    then
	tmp=`bash $AIP_DIR/_aipb_gettempdir`
	
	cat "$PKG_INFO/$remove_p1" | bzip2 -d > "$tmp/rm_list"
	cat "$tmp/rm_list" | sed -e "s/^/ rm -v \"$DESTDIR/;s/\$/\"/"  > "$tmp/mrm_list"
	bash "$tmp/mrm_list"
	
	rm -r "$tmp"
	unset tmp
    fi

    rm "$PKG_INFO/buildlogs/$remove_p1"
    rm "$PKG_INFO/sums/$remove_p1"
    rm "$PKG_INFO/$remove_p1"

    return 0
}

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'remove' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

. "$AIP_DIR/_aipb_init"

if [ -n "$DESTDIR" -a ! -a "$DESTDIR" ]
then
    echo "*** DESTDIR is set, but does not exists"
    exit 1
fi

if [ -n "$DESTDIR" -a ! -d "$DESTDIR" ]
then
    echo "*** DESTDIR is set, exists, but isn't directory"
    exit 1
fi

cd "$PKG_INFO"
pwd
set -f
echo "searching for: $@"
b_filelist=
for b_i in $@
do
    b_filelist="$b_filelist `find . -maxdepth 1 -type f -name \"$b_i\" -printf \" %f\" ` "
#    find . -maxdepth 1 -type f -name "$b_i" -printf " %f"
done

set +f
echo "found: $b_filelist"

for b_i in $b_filelist
do
    remove_p1="$b_i"
    remove
done

err=$?

echo "ldconfig"
ldconfig
echo "sync"
sync
     
exit $err