#!/bin/bash

# this tool converts all symbolic links in current dir from direct to
# relative

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

PPWD=`pwd`

find -type l -exec bash -c "set -x ; linkname='{}' ; oldlvalue=\`readlink \"\$linkname\"\` ; oldlvaluefn=\`basename \"\$oldlvalue\"\` ; newlvalue=\"./\$oldlvaluefn\" ; echo \"\$oldlvalue\" |  grep -q \"^$PPWD\" ; if [ \$? -eq 0 ] ; then rm \"\$linkname\" ; ln -s \"\$newlvalue\" \"\$linkname\"  ; fi " ';'
