#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_pkgnameparse" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_pkgnameparse]"
    exit 1
fi

sif=

case "$1" in
    '-min')
	sif="-lt"
	shift
	;;
    '-max')
	sif="-gt"
	shift
	;;
    '--help')
	echo -e "usage: aipsetup pvc { -min | -max } name filenames"
	echo
	echo -e "\twhere:"
	echo -e "\t\t-min\t\tsearch for minimal package version"
	echo -e "\t\t-max\t\tsearch for maximal package version"
	echo -e "\t\tname\t\tpackage name"
	echo -e "\t\tfilenames\tfile names"
	echo
	echo -e "example: aipsetup pvc -max pidgin *.bz2"
	exit 0
	;;
    *)
	echo "first parameter must be '-min' or '-max'"
	exit 1
	;;
esac

name="$1"
shift

# first time mutch found loop flag
first_time=1

out_filename=
out_vcount=
for (( i=0 ; i != 10 ; i++))
do
    out_v[$i]=0
done

for i in $*
do
    fnameinfo=`bash "$AIP_DIR/_aipb_pkgnameparse" "$i"`
    pname=`echo "$fnameinfo" | grep -e "^n:" | sed -e "s/^n://"`
    if [ $pname = $name ]
    then
	if [ $first_time -eq 1 ]
	then
	    first_time=0
	    out_filename=$i
	    out_vcount=`echo "$fnameinfo" | grep -e "^vc:" | sed -e "s/^vc://"`
	    for (( j=0 ; j != out_vcount ; j++ ))
	    do
		out_v[$j]=`echo "$fnameinfo" | grep -e "^v$j:" | sed -e "s/^v$j://"`
	    done
	else
	    for (( j=0 ; j != 10 ; j++))
	    do
		in_v[$j]=0
	    done

	    in_vcount=`echo "$fnameinfo" | grep -e "^vc:" | sed -e "s/^vc://"`
	    
	    for (( j=0 ; j != in_vcount ; j++ ))
	    do
		in_v[$j]=`echo "$fnameinfo" | grep -e "^v$j:" | sed -e "s/^v$j://"`
	    done

	    if [ $out_vcount -gt $in_vcount ]
	    then
		c_vcount=$out_vcount
	    else
		c_vcount=$in_vcount
	    fi
	    
	    for (( i_vcount=0 ; i_vcount != c_vcount ; i_vcount++ ))
	    do
		if [ "${in_v[$i_vcount]}" -eq "${out_v[$i_vcount]}" ]
		then
		    continue
		fi
		if [ "${in_v[$i_vcount]}" $sif "${out_v[$i_vcount]}" ]
		then
		    out_filename=$i
		    for (( o=0 ; o != 10 ; o++))
		    do
			out_v[$o]=0
		    done
		    out_vcount=`echo "$fnameinfo" | grep -e "^vc:" | sed -e "s/^vc://"`
		    for (( o=0 ; o != out_vcount ; o++ ))
		    do
			out_v[$o]=`echo "$fnameinfo" | grep -e "^v$o:" | sed -e "s/^v$o://"`
		    done
		    break
		    else
		    break
		fi
	    done
	fi
    fi
done

echo "$out_filename"

exit 0