#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

while true
do
    c="`dd bs=1 count=1 status=noxfer 2>/dev/null`"
    if [ "$c" == "`echo -e \"\x00\"`"  ]
    then
	break
    else
	echo -n "$c"
    fi
done

exit 0
