#!/bin/bash

# this script will migrate you'r system from bzip2 aipsetup to xz
# aipsetup

# aipsetup

ppwd="`pwd`"

BASEDIR=/

if [ "$1" = "-b" ]
then
    BASEDIR="$2"
    shift 2
fi

if [ ! -d "$BASEDIR/var/log/packages" ]
then
    echo "basedir with packages not exists"
    exit 1
fi

if [ ! -d "$BASEDIR/var/log/packages/buildlogs" ]
then
    echo "basedir with packages not exists"
    exit 1
fi

if [ ! -d "$BASEDIR/var/log/packages/sums" ]
then
    echo "basedir with packages not exists"
    exit 1
fi

echo "this script will migrate you'r system from bzip2 aipsetup to xz"
echo "aipsetup"
echo
echo "base dir is $BASEDIR"
echo
echo "type 'yes',ENTER and ctrl+d to continue, or abort operation (ctrl+c)"

ans=`cat`

myproc_v1=
function myproc() {
    cd "$myproc_v1"
    if [ "$?" -eq 0 ]
    then
	find -maxdepth 1 -type f -name '*.bz2' -print -exec bash -c " cat '{}' | bzip2 -d | xz -v9M \"\$((200*1024*1024))\" > tmp  ; mv tmp \"\`echo '{}' | sed -e 's,.bz2$,.xz,' \`\"  " ';'
    else
	echo "error processing $myproc_v1"
	return 1
    fi
    return 0
}

if [ "$ans" == 'yes' ]
then
    myproc_v1="$BASEDIR/var/log/packages/buildlogs"
    myproc
    if [ "$?" -ne 0 ]
    then
	exit 1
    else
	myproc_v1= "$BASEDIR/var/log/packages/sums"
	myproc
	if [ "$?" -ne 0 ]
	then
	    exit 1
	else
	    myproc_v1= "$BASEDIR/var/log/packages"
	    myproc
	    if [ "$?" -ne 0 ]
	    then
		exit 1
	    else
		find -type f -name '*.bz2' -exec rm -v '{}' ;
	    fi	    
	fi
    fi
fi
