#!/bin/bash

# This script searches all soft links with pwd in the link and removes
# this pwd from link


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

PPWD=`pwd`

find -type l -exec bash "$AIP_DIR/_aipb_fixsoftlink" '{}' ';'

exit 0