#!/bin/bash

# this script escepes all slashes in first parameter and gives it to
# stdout. if parameter is not set, then string taken from stdin
	
if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi


p="$1"

# test string
# p='0 / // 123123/14124123//123123/ // / // '

if [ -z "$p" ]
then
    p="`cat`"
    if [ -z "$p" ]
    then
	echo -n "$p"
	exit 0
    fi
fi

pl="${#p}"
nr=

for (( i=0 ; i != pl ; i ++ ))
do
    nr=$nr"${p:$i:1}"
    if [ "${p:$i:1}" == '/'  ]
    then
	nr="$nr/"
    fi
done
echo "$nr"

exit 0
