#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi


ppwd="`pwd`"

for i in $*
do
    if [ ! -f "$i" ]
    then
	echo "file \"$i\" not found"
	continue
    fi
    
    pkgname=`echo "$i" | sed -e 's,.bz2$,,'`

    tmpdir=`"$AIP_DIR/_aipb_gettempdir"`
    if [ "$?" -eq 1 ]
    then
	echo "cant get temp dir"
	continue
    fi

    tmpdir_pkgname="$tmpdir/$pkgname"
    mkdir -p "$tmpdir_pkgname"

    "$AIP_DIR/_aipb_install" -b "$tmpdir_pkgname" "$i"
    
    "$AIP_DIR/_aipb_move_bzip2_to_xz" -b "$tmpdir_pkgname"
    
    cd "$tmpdir_pkgname"
    
    "$AIP_DIR/_aipb_pack"

    cd ../pack

    mv * "$ppwd"
    
    cd "$ppwd"

    rm -r "$tmpdir"
done

exit 0