#!/bin/bash

AIP_DIR="/mnt/sda3/_SRC/_builder/aipsetup"

#set -x

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'remove' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_getarchtype" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_getarchtype]"
    exit 1
fi

standardparser_input_filename=
standardparser_output_name=
standardparser() {
    local i
    local l
    local versions
    local versions2
    local arch
    for (( i=0 ; i != 10 ; i++ ))
    do
	local v[$i]=
    done
    standardparser_input_filename=`basename "$standardparser_input_filename"`
    l=${#standardparser_input_filename}
    for (( i=l-1 ; i != -1 ; i-- ))
    do
	if [ "${standardparser_input_filename:$i:1}" = '-' ]
	then
	    standardparser_output_name=${standardparser_input_filename:0:$i}
	    archt=`bash "$AIP_DIR/_aipb_getarchtype" "$standardparser_input_filename"`
	    versions=` echo "$standardparser_input_filename" | sed -e "s/^$standardparser_output_name.//;s/\.$archt\$//"`
	    break
	fi
    done
    versions2=`echo "$versions" | sed -e "s/\./ /g"`
    i=0
    for l in $versions2
    do
	v[$i]=$l
	i="$(( $i + 1 ))"
    done
    echo "s:$standardparser_input_filename"
    echo "n:$standardparser_output_name"
    echo "a:$archt"
    echo "v:$versions"
    echo "vv:$versions2"
    echo "vc:$i"
    for (( l=0 ; l != i; l++ ))
    do
	echo "v$l:${v[$l]}"
    done
    echo
}

for base_i in $*
do
    standardparser_input_filename=$base_i
    standardparser
done