#!/bin/bash

#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

PPWD=`pwd`

check_p1=
check() {
    
    if [ ! -f "$PKG_INFO/sums/$check_p1" ]
    then
	echo " ERROR: file $PKG_INFO/sums/$check_p1 not found"
	return 1
    fi
    basename "$check_p1" .xz
    if [ $? -ne 0 ]
    then
	echo " ERROR: wrong checksum file"
	return 1
    fi

    cat "$PKG_INFO/sums/$check_p1" | xz -d | sha512sum -c 
    
    if [ $? -eq 0 ]
    then
	echo " all ok"
	return 0
    else
	echo " errors found"
	return 1
    fi
}



if [ -n "$DESTDIR" -a ! -a "$DESTDIR" ]
then
    echo "*** DESTDIR is set, but does not exists"
    exit 1
fi

if [ -n "$DESTDIR" -a ! -d "$DESTDIR" ]
then
    echo "*** DESTDIR is set, exists, but isn't directory"
    exit 1
fi

check_p1="$1"
check
     
exit $?