#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

FILENAME="$1"

if [ ! -d "$2" ]
then
    DESTDIR='.'
else
    DESTDIR="$2"
fi

if [ -f "$FILENAME" ]
then
    ARCH_TYPE=`bash "$AIP_DIR/_aipb_getarchtype" "$FILENAME"`

    if [ $? -eq 0 ]
    then
	case $ARCH_TYPE in
	    'tar.gz' | 'tgz')
		set -o pipefail
		cat "$FILENAME" | gzip -d | tar -xvC "$DESTDIR"
		set +o pipefail
		fail=$?
		;;
	    'tar.bz2')
		set -o pipefail
		cat "$FILENAME" | bzip2 -d | tar -xvC "$DESTDIR"
		set +o pipefail
		fail=$?
		;;
	    'tar.lzma')
		set -o pipefail
		cat "$FILENAME" | lzma -d | tar -xvC "$DESTDIR"
		set +o pipefail
		fail=$?
		;;
	    'tar.xz')
		set -o pipefail
		cat "$FILENAME" | xz -d | tar -xvC "$DESTDIR"
		set +o pipefail
		fail=$?
		;;
	    'tar.7z')
		set -o pipefail
		7z x -so "$FILENAME" | tar -xC "$DESTDIR"
		set +o pipefail
		fail=$?
		;;
	    'zip')
		unzip -qq "$FILENAME" -d "$DESTDIR"
		fail=$?
		;;
	    *)
		echo "unknown extention"
		exit 1
		;;
	esac
	if [ "$fail" -ne 0 ]
	then
	    echo "file extraction error"
	fi
	exit $fail
    else
	echo "unknown extention"
    fi
else
    echo "file \"$FILENAME\" not exists"
fi
exit 0