#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

# this program searchs given file in packages installation logs

cd "$PKG_INFO"
find -maxdepth 1 -name '*.bz2' -exec bash -c " cat '{}' |  bzip2 -d | grep '$1' ; e=\$? ; if [ \$e -eq 0 ] ; then echo -e 'found $1 in: {}\n' ; fi  " ';'
echo "search complite"
exit 0
