#!/bin/bash

if [ ! -w "/tmp" ]
then
    echo " ERROR: to create temporary dir I need /tmp to be writable by Me"
    exit 1
fi

DATE=`date '+%Y%m%d%H%M%S'`
NAME="/tmp/aipsetup-$DATE"

mkdir -p "$NAME" > /dev/null 2>&1
err=$?
if [ $err -eq 0 ]
then
    echo "$NAME"
    exit 0
fi
exit 1