#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_extract" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_extract]"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_script" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_script]"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_pack" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_script]"
    exit 1
fi

if [ ! -f "$1" ]
then
    echo "file \"$1\" not found"
    exit 1
fi

if [ -z "$2" ]
then
    echo "dir not defined"
    exit 1
fi

if [ -z "$3" ]
then
    echo "template not defined"
    exit 1
fi

echo "extracting"
bash "$AIP_DIR/_aipb_extract" "$1"
if [ $? -ne 0 ]
then
    echo "can't extract \"$1\""
    exit 1
fi

echo "searching"
ardir="`find -maxdepth 1 -type d -name \"$2\"`"

if [ ! -d "$ardir" ]
then
    echo "dir not found \"$ardir\""
    exit 1
fi

echo "buiding in \"$ardir\""

cd  "$ardir"

bash "$AIP_DIR/_aipb_script" "$3"

if [ $? -ne 0 ]
then
    echo "can't create template \"$3\""
    exit 1
fi

bash "_tnbuild_$3"
if [ $? -ne 0 ]
then
    echo "error while running build in templete"
    exit 1
fi

cd ..

ardir=`cat "lastresultdir"`

if [ ! -d "$ardir" ]
then
    echo "dir not found \"$ardir\""
    exit 1
fi

echo "packing \"$ardir\""
cd  "$ardir"

bash "$AIP_DIR/_aipb_pack"

if [ $? -ne 0 ]
then
    echo "error while packing"
    exit 1
fi


cd ..