#!/bin/bash

#!/bin/bash

PPWD=`pwd`

check_p1=
check() {
    
    if [ ! -f "$PKG_INFO/sums/$check_p1" ]
    then
	echo " ERROR: file $PKG_INFO/sums/$check_p1 not found"
	return 1
    fi
    basename "$check_p1" .bz2
    if [ $? -ne 0 ]
    then
	echo " ERROR: wrong checksum file"
	return 1
    fi

    cat "$PKG_INFO/sums/$check_p1" | bzip2 -d | sha512sum -c 

    return $?
}

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'remove' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

. "$AIP_DIR/_aipb_init"

if [ -n "$DESTDIR" -a ! -a "$DESTDIR" ]
then
    echo "*** DESTDIR is set, but does not exists"
    exit 1
fi

if [ -n "$DESTDIR" -a ! -d "$DESTDIR" ]
then
    echo "*** DESTDIR is set, exists, but isn't directory"
    exit 1
fi

check_p1="$1"
check
     
exit $?