#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_extract" ]
then
    echo " ERROR: '$AIP_DIR/_aipb_extract' not found"
    exit 1
fi

if [ "$1" = "-b" ]
then
    BASEDIR="$2"
    mkdir -p "$BASEDIR"
    shift 2
else
    unset BASEDIR
fi

PPWD=`pwd`

OKi=0
ERi=0

filebname=
dirbname=
for i in $*
do
    if [ -f "$i" ]
    then
	filebname=`basename "$i"`
	dirbname=`dirname "$i"`
	cd "$dirbname"
	printf "installing: \"$filebname\"...\n"
	if [ -n "$BASEDIR" ]
	then
	    echo "        to:\"$BASEDIR\""
	fi
	printf "     md5:"
	md5sum -c "$filebname".md5
	if [ $? -ne 0 ]
	then
	    echo "error"
	    ERi=$(( $ERi + 1 ))
	    continue
	fi

	printf "  sha512:"
	sha512sum -c "$filebname".sha512
	if [ $? -ne 0 ]
	then
	    echo "error"
	    ERi=$(( $ERi + 1 ))
	    continue
	fi

	echo -n "      installing:"
	bash "$AIP_DIR/_aipb_extract" "$filebname" "$BASEDIR"/
	if [ $? -eq 0 ]
	then
	    printf ":OK\n"
	    OKi=$(( $OKi + 1 ))
	else
	    printf ":ERROR\n"
	    ERi=$(( $ERi + 1 ))
	fi
	cd "$PPWD"
    fi
done
echo "  installed: $OKi, errors: $ERi, Total: $(( $OKi + $ERi ))"
if [ -z "$BASEDIR" ]
then
    echo "ldconfig"
    ldconfig
fi
echo "sync"
sync


