#!/bin/bash

# this script looking for files, openable by ldd, depenfing on given
# file


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

filename=$1
theretosearch=$2

ppwd=`pwd`

cd "$theretosearch"
find -maxdepth 1 -type f -exec bash -c " ldd '{}' | grep '$filename' 2>&1 > /dev/null ; if [ $? -eq 0 ] ; then echo '{}' ; fi  " ';'

cd "$ppwd"
