#!/bin/bash

# This script searches all soft links with pwd in the link and removes
# this pwd from link


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

linkname=$1
linkvalue=`readlink "$linkname"`
linkvaluel="${#linkvalue}"
PPWD=`pwd`
PPWDL="${#PPWD}"

echo "$linkvalue" | grep "^$PPWD" 2>&1 > /dev/null
pwdfound="$?"

if [ "$pwdfound" -eq 0 ]
then
    linkvalueremain="$(( $linkvaluel - $PPWDL ))"
    newlink="${linkvalue:PPWDL:linkvalueremain}"
    rm -v "$linkname"
    ln -v -s "$newlink" "$linkname"
fi

exit 0