#!/bin/bash


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

echo 'changing owner'
chown -R 0:0 *
echo 'changing rules'
chmod -R 755 *

PPWD=`pwd`
PKGNAME=`basename $PPWD`

FILEDIR=./var/log/packages
FILELIST="$FILEDIR/$PKGNAME"

echo "Creating package: $PKGNAME..."
echo "  creating installation file list"
mkdir -p "$FILEDIR" > /dev/null 2> /dev/null
rm  "$FILEDIR"/* > /dev/null 2> /dev/null

touch "$FILELIST"
find ./ '(' '(' -type f -o -type l ')' -a '(' ! -regex '.*/var/log/packages.*' ')' ')' | sed -e "s/^\.//g" >> "$FILELIST"
 
cat "$FILELIST" | sort > "$FILELIST"1
cat "$FILELIST"1 > "$FILELIST"
rm "$FILELIST"1

bzip2 -9 "$FILELIST"

bash "$AIP_DIR/_aipb_pksums"


mkdir ../pack > /dev/null 2> /dev/null

echo "   tarring..."
tar --exclude _aipb_pack -c * | xz -v9M "$(( 200*1024*1024 ))" | sed -e 's/\.\.\/pack\//\.\//'  > "../pack/$PKGNAME.tar.xz"
echo "     md5..."
md5sum -b "../pack/$PKGNAME.tar.xz" | sed -e 's/\.\.\/pack\//\.\//'  > "../pack/$PKGNAME.tar.xz.md5"
echo "     sha512sum..."
sha512sum -b "../pack/$PKGNAME.tar.xz" | sed -e 's/\.\.\/pack\//\.\//'  > "../pack/$PKGNAME.tar.xz.sha512"

echo "done"
exit 0