#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

# this file lists packages installed in system.  -b parameter can be
# used to change system base dir ( by default / ).

set -f

unset BASEDIR
if [ "$1" = "-b" ]
then
    BASEDIR="$2"
    shift 2
fi

cd "$BASEDIR/$PKG_INFO"

if [ $? -eq 0 ]
then
    if [ -z "$1" ]
    then
	LIST=`find -maxdepth 1 -type f -name '*.xz' | sort`
    else
	set -f
	LIST=`find -maxdepth 1 -type f -name "$1" | sort `
    fi
    for i in $LIST
    do
	stat --printf="%n\n" "$i" # \t Changed: \"%z\"\n" "$i"
    done
else
    echo "can't cd to packages dir"
    exit 1
fi
exit 0
