#!/bin/bash

# This script searches all soft links with pwd in the link and removes
# this pwd from link


if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

PPWD=`pwd`

echo searching for "$PPWD" in files to remove it.

echo fixing links...
find -type l -exec bash "$AIP_DIR/_aipb_fixsoftlink" '{}' ';'

cd usr

echo fixing files...
find -type f -exec bash -c '  grep '"$PPWD"'  "{}"  > /dev/null  ; e="$?" ; if [ "$e" -eq 0 ] ; then echo "editing {}" ; sed -i -e "s|'"$PPWD"'||g" "{}" ; fi ' ';'

exit 0