#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run 'remove' from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -f "$AIP_DIR/_aipb_pkgnametool" ]
then
    echo " ERROR: can't find [$AIP_DIR/_aipb_pkgnametool]"
    exit 1
fi
