#!/bin/bash

if [ ! -d "$AIP_DIR" ]
then
    echo " SORRY: please, install aipsetup (if not yet),"
    echo "        and run this from main program (aipsetup)"
    echo " ERROR: AIP_DIR not set"
    exit 1
fi

if [ ! -w "`pwd`" ]
then
    echo " ERROR: to create temporary dir I need current directory to be writable by Me"
    exit 1
fi

DATE=`date '+%Y%m%d%H%M%S'`
NAME="`pwd`/aipsetup-$DATE"

mkdir -p "$NAME" > /dev/null 2>&1
err=$?
if [ $err -eq 0 ]
then
    echo "$NAME"
    exit 0
fi
exit 1