#!/bin/bash

#this will be changed during 'make install'
export AIP_DIR=""

if [ ! -d "$AIP_DIR" ]
then
    echo "\$AIP_DIR variable not set, please use 'make install' in the source directory"
    exit 1
fi

case "$#" in
    0)
	echo "not enough parameters, use --help for info"
	;;
    *)
	case "$1" in
	    --version)
		printf "aipsetup " 
		cat "$AIP_DIR/VERSION"
		echo
		echo -e "Copyright (C) 2008,2009 AGUtilities Software, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE."
		exit 0
		;;
	    --help)
		echo -e "usage: `basename $0` [command] [command_parameters]"
		echo
		echo -e "[command]s:"
		echo -e "  building tools:"
		echo -e "\tesc|escript\t\tedit script compiler"
		echo -e "\t sc|script\t\tuse script compiler"
		echo -e "\t\t\t\t(see \``basename $0` script --help')"
		echo -e "\tpks|pksums\t\tcreate sha512 sums for current dir"
		echo -e "\t lf|lnfix\t\tfix symlinks in current dir"
		echo -e "\t pk|pack\t\tpack current dir"
		echo -e "\t bd|build arch ardir templ abdir\t\tpack current dir"
		echo 
		echo -e "  aipsetup system tools:"
		echo -e "\tcsc|cscript\t\tcopy builder script to current"
		echo -e "\t\t\t\tdir (for maintainers)"
		echo 
		echo -e "  system tools:"
		echo -e "\t ls|list [filemask]\tlist installed packages"
		echo -e "\tchk|pkcheck TARGET\tcheck pkg sums"
		echo -e "\t rm|remove [filemask]\tremove named package"
		echo -e "\t in|install FILE\tinstall named package files"
		echo -e "\t fn|findcom FILENAME\tfind package by FILENAME"
		echo -e "\tldd|lddsums PROGRAM\tmake sha512 sums for PROGRAM ldd output"
		echo
		echo -e "  misc tools:"
		echo -e "\t ex|extract FILE\textract to the current dir"
		echo -e "\t np|nameparse\t\tparse package filename"
		echo -e "\t lu|listuniq\t\tparse package filenames and show all uniq names"
		echo -e "\tpvc|pkgnamevcomp\tfind newest or oldest package from given by name (see --help)"
		echo -e "\tllu|pkgnamelstlat\tlist all latest packages of given"
		echo
		echo
		echo -e "\t--help\t\t\tsee this help"
		echo -e "\t--version\t\tversion info"
		exit 0
		;;

	    escript | esc)
		if [ -z "$VISUAL" ]
		then
		    echo " VISUAL not defined"
		    exit 1
		fi
		if [ -z "$2" ]
		then
		    "$VISUAL" "$AIP_DIR/_aipb_script"
		else
		    if [ ! -f "$AIP_DIR/templates/$2" ]
		    then
			cp "$AIP_DIR/templates/usr" "$AIP_DIR/templates/$2"
		    fi
		    "$VISUAL" "$AIP_DIR/templates/$2"
		fi
		exit $?
		;;
	    script | sc)
		shift
		bash "$AIP_DIR/_aipb_script" $*
		exit $?		
		;;
	    bd | build)
		shift
		bash "$AIP_DIR/_aipb_build" $*
		exit $?
		;;
	    pksums | pks)
		shift
		bash "$AIP_DIR/_aipb_pksums " $*
		exit $?
		;;
	    lnfix | lf)
		shift
		bash "$AIP_DIR/_aipb_slinksa2r" $*
		exit $?
		;;
	    pack | pk)
		shift
		bash "$AIP_DIR/_aipb_pack" $*
		exit $?
		;;

	    cscript | csc)
		cp -r "$AIP_DIR/templates" .
		exit 0
		;;

	    list | ls)
		shift
		set -f
		bash "$AIP_DIR/_aipb_list" $*
		set +f
		exit $?				
		;;
	    pkcheck | chk)
		shift
		set -f
		bash "$AIP_DIR/_aipb_checksums" $*
		set +f
		exit $?				
		;;
	    remove | rm)
		shift
		set -f
		bash "$AIP_DIR/_aipb_remove" $*
		set +f
		exit $?				
		;;
	    install | 'in')
		shift
		bash "$AIP_DIR/_aipb_install" $*
		;;
	    findcom | fn)
		shift
		bash "$AIP_DIR/_aipb_fpbf" $*
		exit $?
		;;
	    lddsums | 'ldd')
		shift
		bash "$AIP_DIR/_aipb_lddsums" $*
		;;

	    extract | ex)
		shift
		bash "$AIP_DIR/_aipb_extract" $*
		exit $?
		;;
	    nameparse | np)
		shift
		bash "$AIP_DIR/_aipb_pkgnameparse" $*
		exit $?
		;;
	    listuniq | lu)
		shift
		bash "$AIP_DIR/_aipb_pkgnamelistuniq" $*
		exit $?
		;;
	    pvc | pkgnamevcomp)
		shift
		bash "$AIP_DIR/_aipb_pkgnamevcompare" $*
		exit $?
		;;
	    llu|pkgnamelstlat)
		shift
		bash "$AIP_DIR/_aipb_pkgnamelistalllatestuniq" $*
		exit $?
		;;
	    *)
		echo "wrong parameter, use --help for info"
		exit 0
		;;
	esac
	;;
esac 

exit 0