#!/bin/bash

#this will be changed during 'make install'
AIP_DIR=""

if [ ! -d "$AIP_DIR" ]
then
    echo "\$AIP_DIR variable not set, please use 'make install' in the source directory"
    exit 1
fi

case "$#" in
    0)
	echo "not enough parameters, use --help for info"
	;;
    *)
	case "$1" in
	    --version)
		printf "aipsetup " 
		cat "$AIP_DIR/VERSION"
		exit 0
		;;
	    --help)
		echo -e "usage: `basename $0`"
		echo
		echo -e "\tcsc|cscript\t\tcopy builder script to current dir"
		echo -e "\tesc|escript\t\tedit builder script"
		echo -e "\tsc|script\t\tuse builder script (see $0 script --help)"
		echo -e "\tpk|pack\t\t\tuse packing script"
		echo -e "\tls|list\t\t\tlist installed packages"
		echo -e "\trm|remove TARGET\tremove named package"
#		echo -e "\tin|install FILE\t\tinstall named package file"
		echo -e "\tfn|findcom FILENAME\t\tfind package by FILENAME"
		echo 
		echo -e "\tex|extract FILE\t\textract to the current dir"
		echo
		echo -e "\t--help\tsee this help"
		echo -e "\t--version\tversion info"
		exit 0
		;;
	    cscript | csc)
		cp "$AIP_DIR/_aipb_script" .
		exit $?
		;;
	    escript | esc)
		"$VISUAL" "$AIP_DIR/_aipb_script"
		exit $?
		;;
	    list | ls)
		shift
		cd /var/log/packages
		bash "$AIP_DIR/_aipb_list" $*
		exit $?				
		;;
	    remove | rm)
		shift
		cd /var/log/packages
		bash "$AIP_DIR/_aipb_remove" $*
		exit $?				
		;;
	    script | sc)
		shift
		bash "$AIP_DIR/_aipb_script" $*
		exit $?		
		;;
	    extract | ex)
		shift
		bash "$AIP_DIR/_aipb_extract" $*
		exit $?
		;;
	    pack | pk)
		shift
		bash "$AIP_DIR/_aipb_pack" $*
		exit $?
		;;
	    findcom | fn)
		shift
		bash "$AIP_DIR/_aipb_fpbf" $*
		exit $?
		;;
	    *)
		echo "wrong parameter, use --help for info"
		exit 0
		;;
	esac
	;;
esac 

exit 0