#!/usr/bin/python

import getopt
import os
import os.path
import sys

import aipsetup.utils
import aipsetup.build

try:
    optilist, args = getopt.getopt(sys.argv[1:],
                                   'v',
                                   ['smode=', 'mode=', 
                                    'verbose'])

except getopt.GetoptError, e:
    print '-e- Error while parsing parameters: ' + e.msg
    exit(1)

mode=aipsetup.utils.option_check(['--mode', '-m'], optilist)
smode=aipsetup.utils.option_check(['--smode', '-s'], optilist)
verbose_option=aipsetup.utils.option_check(['--verbose', '-v'], optilist)

ret = 0                         # default return value

if not mode[0] or not smode[0]:
    print '-e- mode and submode must be set'
    exit(1)

if mode[2] == 'build' and smode[2] == 'init':

    init_dir = 'tmp'
    if len(args) == 1:
        init_dir = args[0]

    if len(args) > 1:
        print '-e- too many arguments'
        exit(1)

    ret = aipsetup.build.init(directory=init_dir, verbose=verbose_option[0])

if mode[2] == 'utils' and smode[2] == 'pkg_name_parse':

    if len(args) != 1:
        print '-e- exectly one argument required'
        exit(1)

    ret = aipsetup.utils.pkg_name_parse(args[0])

print '-i- end'
exit(ret)
