#!/bin/bash
#####                    USER editing part:
# Settings, making all tha passion on the rest of the actions
export HOSTOPT=i686
export OTHEROPTS="--prefix=/usr/games/vega --datadir=/usr/games/vega/data"
unset FLAGS
export ACTIONDIR=`pwd`
new_base=`basename $ACTIONDIR-$HOSTOPT`
parent_dir=`dirname $ACTIONDIR`


##### this is not for editing!!
if [ -z "$FLAGS" ]
then
    unset FLAGS
    unset CFLAGS
    unset LDFLAGS
    unset CPPFLAGS
    unset CXXFLAGS
else
    export CFLAGS=$FLAGS
    export LDFLAGS=$FLAGS
    export CPPFLAGS=$FLAGS
    export CXXFLAGS=$FLAGS
fi
##### "this is not for editing!!" section ended

./configure $OTHEROPTS --host=$HOSTOPT-pc-linux-gnu
err=$?
if [ $err -eq 0 ]
then
    make clean
    make
    err=$?
    if [ $err -eq 0 ]
    then
	make install DESTDIR=\"$parent_dir/$new_base\"
    else
	exit 1
    fi
else
    exit 1
fi
exit 0
