#!/bin/bash

#####                    USER editing part:
# Settings, making all the passion on the rest of the actions
export HOSTOPT=i486
export OTHEROPTS="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared"
unset FLAGS
export ACTIONDIR=`pwd`
new_base=`basename $ACTIONDIR-$HOSTOPT`
parent_dir=`dirname $ACTIONDIR`


##### this is not for editing!!
if [ -z "$FLAGS" ]
then
    unset FLAGS
    unset CFLAGS
    unset LDFLAGS
    unset CPPFLAGS
    unset CXXFLAGS
else
    export CFLAGS=$FLAGS
    export LDFLAGS=$FLAGS
    export CPPFLAGS=$FLAGS
    export CXXFLAGS=$FLAGS
fi
##### "this is not for editing!!" section ended

./configure $OTHEROPTS --host=$HOSTOPT-pc-linux-gnu
err=$?
if [ $err -eq 0 ]
then
    make clean
    make
    err=$?
    make check 2>&1 | tee ../check_log
    if [ $err -eq 0 ]
    then
	make install INSTALLROOT="$parent_dir/$new_base"
    else
	exit 1
    fi
else
    exit 1
fi
exit 0
