#!/bin/bash
apacheant() {
    PACKAGENAME='apache-ant'
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-java-sun"
    SEPARATEDIR=0
    RELATIVE='.'
    
    local j=0
    RUN[$j]='build.sh'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some build error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/usr/lib/apache-ant" ; cp -a dist/* "$bs_install_dir/usr/lib/apache-ant" ; mkdir -p "$bs_install_dir/etc/profile.d"  ; printf "export ANT_HOME=/usr/lib/apache-ant \nexport PATH=\"\$PATH:/usr/lib/apache-ant/bin\" \n " > "$bs_install_dir/etc/profile.d/apache-ant.sh" ; chmod 755 "$bs_install_dir/etc/profile.d/apache-ant.sh" ; mkdir -p "$bs_install_dir/usr/share/doc/apache-ant" ; cp -a docs/* "$bs_install_dir/usr/share/doc/apache-ant"  # '
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=0
}
