#!/bin/bash
boost() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'
    
    local j=0
    RUN[$j]='bootstrap.sh'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='bjam --prefix=/usr'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some bjam error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='bjam --prefix="$bs_install_dir/usr"'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='pppp="`pwd`" ; cd $bs_install_dir/usr/include/ ; ln -s ./boost*/boost* ./boost ; cd "$pppp" '
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}

