#!/bin/bash
bzip2() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]="cat ./Makefile | sed -e \"s#PREFIX=/usr/local#PREFIX=/usr#\" | sed -e \"s#CFLAGS=-Wall -Winline -O2 -g \\\$(BIGFILES)#CFLAGS=-Wall -Winline -O2 -g \\\$(BIGFILES) -march=i486 -mtune=i486#\"  > Makefile2 #"
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** configuring error'
    EXITONERROR[$j]=0


    j=$(( $j + 1 ))
    RUN[$j]="mv Makefile2 Makefile #"
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** configuring file error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]="cat ./Makefile-libbz2_so | sed -e \"s#PREFIX=/usr/local#PREFIX=/usr#\" | sed -e \"s#CFLAGS=-Wall -Winline -O2 -g \\\$(BIGFILES)#CFLAGS=-Wall -Winline -O2 -g \\\$(BIGFILES) -march=i486 -mtune=i486#\"  > Makefile-libbz2_so2 #"
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** configuring error'
    EXITONERROR[$j]=0


    j=$(( $j + 1 ))
    RUN[$j]="mv Makefile-libbz2_so2 Makefile-libbz2_so #"
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** configuring file error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make install PREFIX="$bs_install_dir/usr"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make -f Makefile-libbz2_so'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error Makefile-libbz2_so'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='cp -P *.so.* "$bs_install_dir/usr/lib"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error Makefile-libbz2_so'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='cd "$bs_install_dir/usr/bin" ; aipsetup lf ; cd ~- # '
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='fix links error'
    EXITONERROR[$j]=0
}
