#!/bin/bash

bzip2() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]="make PREFIX=/usr CFLAGS=\"-Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -march=i486 -mtune=i486\" "
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make install PREFIX="$bs_install_dir/usr"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make -f Makefile-libbz2_so CFLAGS="-Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64 -march=i486 -mtune=i486"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some lib make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='cp -P *.so.* "$bs_install_dir/usr/lib"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some lib install error Makefile-libbz2_so'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='cd "$bs_install_dir/usr/bin" ; aipsetup lf ; cd ~- '
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='fix links errors'
    EXITONERROR[$j]=0
}
