#!/bin/bash

erlang() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='configure --with-termcap --enable-threads --with-ssl --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared --host=i486-pc-linux-gnu'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='export INSTALL_PREFIX="$bs_install_dir" #'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]=''
    # EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make install INSTALL_PREFIX="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

     j=$(( $j + 1 ))
     t="cat '{}' | sed -e \\\"s,\$bs_install_dir,,\\\" > tmpf ; mv tmpf '{}' "
     t2="f1=\\\`leadlink '{}'\\\` ; f2=\\\`echo \\\"\\\$f1\\\" | sed -e \\\"s,\$bs_install_dir,,\\\" \\\` ; rm '{}' ; ln -s \\\"\\\$f2\\\" '{}' "
     RUN[$j]="cd \"\$bs_install_dir\usr\" ; find -type f  -exec bash -c \"$t\" ';' ; find -type l -exec bash -c \"$t2\" ';' #"
     RELATIVELY[$j]=0
     ERRORMESSAGE[$j]='*** some make install error'
     EXITONERROR[$j]=1
}
