#!/bin/bash

exaile() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='make ; make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
#    RUN[$j]='make install DESTDIR="$bs_install_dir/usr" LIBDIR="$bs_install_dir/usr/lib" FIREFOX="$bs_install_dir/usr/lib/firefox"'
    RUN[$j]='make install DESTDIR="$bs_install_dir" LIBDIR="/lib" FIREFOX="/usr/lib/firefox" PREFIX=/usr'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
