#!/bin/bash

firefox() {
    PACKAGENAME=firefox
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=1
    RELATIVE='.'
    
    local j=0
    # RUN[$j]='mkdir -p "$bs_build_dir"'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some make error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='cd "$bs_run_dir" #'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some make error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]="echo -e \"mk_add_options MOZ_OBJDIR='\$bs_build_dir' \nac_add_options --enable-application=suite \nac_add_options --enable-optimize \nac_add_options --enable-default-toolkit=cairo-gtk2 \nac_add_options --enable-xft \nac_add_options --enable-freetype2\" > \"\$bs_run_dir/.mozconfig\" #"
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some configure script error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='make -f "client.mk" build'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some make error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='cd "$bs_build_dir" #'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some make error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    RUN[$j]='configure --enable-optimize --enable-default-toolkit=cairo-gtk2 --enable-xft --enable-freetype2  --enable-application=browser --disable-ldap --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared --with-system-jpeg --with-system-zlib --with-system-bz2 --host=i486-pc-linux-gnu'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='configure --enable-application=suite --disable-ldap --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared --host=i486-pc-linux-gnu'
    # RELATIVELY[$j]=1
    # ERRORMESSAGE[$j]='*** some configure script error'
    # EXITONERROR[$j]=1

    
    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=0
    
    j=$(( $j + 1 ))
    RUN[$j]='make install DESTDIR="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
