#!/bin/bash

glibc() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=1
    RELATIVE='.'

    local j=0
    RUN[$j]='echo "CFLAGS += -march=i486 -mtune=native" > configparms #'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='xxx'
    EXITONERROR[$j]=0
    
    j=$(( $j + 1 ))
#    RUN[$j]='configure --without-selinux --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-add-ons  --host=i486-pc-linux-gnu --build=i486-pc-linux-gnu --target=i486-pc-linux-gnu --with-cpu=i486 --with-tls --with-elf'
    RUN[$j]='configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-headers=/usr/src/linux/usr/include --host=i486-pc-linux-gnu --build=i486-pc-linux-gnu --target=i486-pc-linux-gnu --enable-kernel=2.6.31  --with-tls --with-elf'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make install install_root="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}

