#!/bin/bash
httpd() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='configure --with-apr=/usr/bin/apr-1-config --prefix=/usr/share/httpd --libdir=/usr/lib/http --datarootdir=/usr/share/httpd --bindir=/usr/bin --sbindir=/usr/sbin --mandir=/usr/share/man --includedir=/usr/include --oldincludedir=/usr/include --docdir=/usr/share/doc/httpd --dvidir=/usr/share/doc/httpd/dvi --pdfdir=/usr/share/doc/httpd/pdf --psdir=/usr/share/doc/httpd/ps --sysconfdir=/etc/httpd --localstatedir=/var --enable-shared --enable-modules=all --enable-mods-shared=all --enable-so --enable-cgi --enable-ssl --enable-http --enable-info --enable-proxy --enable-proxy-connect --enable-proxy-ftp --enable-proxy-http --enable-proxy-scgi --enable-proxy-ajp --enable-proxy-balancer  --host=i486-pc-linux-gnu --build=i486-pc-linux-gnu'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make install DESTDIR="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
