#!/bin/bash

infozip() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='make -f unix/Makefile generic CFLAGS=" -march=i486 -mtune=i486 "'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some prepair error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make -f unix/Makefile install prefix="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some install error'
    EXITONERROR[$j]=1
}
