#!/bin/bash

iproute2() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --enable-shared --host=i486-pc-linux-gnu --build=i486-pc-linux-gnu'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make KERNEL_INCLUDE=/usr/src/linux/include'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make install DESTDIR="$bs_install_dir" DOCDIR="/usr/share/doc/iproute2" MANDIR="/usr/share/man"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
