#!/bin/bash

jdkbin() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='bash jdk-*-i586.bin<<<yes'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='jdk=`find -maxdepth 1 -type d -name "jdk*"` ; jdk=`echo "$jdk" | sed -e "s/\.\///"` ; bs_install_dir="$bs_parent_dir/$jdk-$bs_pkg_sufix" ;  echo "jdk dir is $jdk" ; echo "New install dir is $bs_install_dir" ; mkdir -pv "$bs_install_dir/usr/lib/java"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='cp -av "$jdk" "$bs_install_dir/usr/lib/java"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/etc/profile.d/SET"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='echo -en "#!/bin/bash\n export PATH="\$PATH:/usr/lib/java/$jdk/bin:/usr/lib/java/$jdk/jre/bin"\n  " > "$bs_install_dir/etc/profile.d/SET/009.java" '
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
