#!/bin/bash

linux() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/usr"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/lib"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1    
    
    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/usr/share/man/man9/"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1    
    
    j=$(( $j + 1 ))
    RUN[$j]='make install INSTALL_PATH="$bs_install_dir/boot"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make headers_install INSTALL_HDR_PATH="$bs_install_dir/usr"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make modules_install INSTALL_MOD_PATH="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make firmware_install INSTALL_MOD_PATH="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make firmware_install INSTALL_MOD_PATH="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make mandocs'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=0
    
    j=$(( $j + 1 ))
    RUN[$j]='cp -v Documentation/DocBook/man/*.9.gz "$bs_install_dir/usr/share/man/man9/"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='***error'
    EXITONERROR[$j]=0
}
