#!/bin/bash

mplayer() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i686-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'
    
    local j=0
    RUN[$j]='configure --prefix=/usr --enable-gui --disable-liba52-internal --enable-radio --enable-radio-capture --enable-radio-v4l2 --enable-tv --enable-tv-v4l1 --enable-tv-v4l2 --enable-network  --enable-vcd  --enable-freetype --enable-ass --enable-gif --enable-png --enable-mng --enable-jpeg --enable-real --enable-xvid-lavc --enable-x264-lavc'
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some configure script error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make check'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='make install DESTDIR="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}

