#!/bin/bash

p7zip() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='make all3 DEST_HOME=/usr'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make install DEST_HOME="$bs_install_dir/usr"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
