#!/bin/bash

setupPYusr() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='python setup.py build'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='make check'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some check error'
    # EXITONERROR[$j]=0

    j=$(( $j + 1 ))
    RUN[$j]='python setup.py install --root="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
