#!/bin/bash

sysvinit() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='src'
    
    local j=0
    RUN[$j]='make CFLAGS=" -Wall -O2 -fomit-frame-pointer -D_GNU_SOURCE -march=i486 -mtune=i486"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/bin" "$bs_install_dir/sbin" "$bs_install_dir/usr/bin" "$bs_install_dir/usr/sbin" "$bs_install_dir/usr/share/man/man1" "$bs_install_dir/usr/share/man/man5" "$bs_install_dir/usr/share/man/man8" "$bs_install_dir/usr/include" "$bs_install_dir/dev"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
    
    j=$(( $j + 1 ))
    RUN[$j]='make install ROOT="$bs_install_dir"'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
