#!/bin/bash

tightvnc() {
    PACKAGENAME=
    PACKAGENAMESUFIX="\`date '+%Y%m%d%H%M%S'\`-i486-pc-linux-gnu"
    SEPARATEDIR=0
    RELATIVE='.'

    local j=0
    RUN[$j]='xmkmf'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some make error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='make World'
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some check error'
    EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='cd Xvnc ; pwd'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some Xvnc cd error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='./configure'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some Xvnc configure error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='make'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some Xvnc make error'
    # EXITONERROR[$j]=1

    # j=$(( $j + 1 ))
    # RUN[$j]='cd .. ; pwd'
    # RELATIVELY[$j]=0
    # ERRORMESSAGE[$j]='*** some pwd error'
    # EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='mkdir -p "$bs_install_dir/usr/bin" "$bs_install_dir/usr/share/man" '
    RELATIVELY[$j]=0
    ERRORMESSAGE[$j]='*** some mkdir error'
    EXITONERROR[$j]=1

    j=$(( $j + 1 ))
    RUN[$j]='vncinstall "$bs_install_dir/usr/bin" "$bs_install_dir/usr/share/man" '
    RELATIVELY[$j]=1
    ERRORMESSAGE[$j]='*** some make install error'
    EXITONERROR[$j]=1
}
